build.application:
	docker-compose up --build

start.application:
	docker-compose up -d

stop.application:
	docker-compose down

test.unit:
	go test ./tests/unit/... -v

test.integration:
	go test ./tests/integration/... -v
